### ISSUE TITLE
ModuleNotFoundError: No module named 'UVToolkit-2.1'

### ISSUE THREAD

**Issue by Kenderator** [oRazeD/UVToolkit#3]
After the classic installation when trying to activate addon (tick), returns this error:

---
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'UVToolkit-2.1'
---

**Comment by oRazeD** [comment]
Hey @Kenderator, I attempted to recreate this error with the Extensions and GitHub builds for UVToolkit 2.1 and 2.1.2 in both Blender 4.0 and 4.2, but I was unable to recreate the issue.

Is there any other information you can offer, like the source of where you got this zip file? Thank you!
